void TetrisApp(void);
void Eventi(void);
void RefreshLine(void);
void ClearLine(void);
void NewBlock(void);
void  DrawNewArray(void);
void GameOverFun(void);
void ClearArray(void);
void CtrlArray(void);
void UpdateArray(void);
unsigned char ReadTouch();
void DrawRandNext(void);
void Tetris(void);
